### ISSUE TITLE
Failure to run NSpecRunner under Microsoft Moles

### ISSUE THREAD

**Issue by algonzalez** [mattflo/NSpec#33]
I'm unable to run NSpecRunner (v0.9.59.0) under Microsoft Moles.

When I issue the command:

```
moles.runner.exe /r:c:\dev\TestProject\tools\nspec\NSpecRunner.exe TestProjectSpec.dll
```

I get the following exception:

```
Microsoft Moles Runner v0.94.51023.0 -- http://research.microsoft.com/moles -- .
NET v4.0.30319
Copyright (c) Microsoft Corporation 2007-2010. All rights reserved.

instrumenting...started

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'file:///c:\dev\TestProject\tools\nspec\NSpecRunner.exe'
 or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm,Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.Moles.Runner.MolesRunner.RunnerRunner.Run(String runner, String[] args)
   at Microsoft.Moles.Runner.MolesRunner.RunnerRunner.Run(String runner, String[] args)
   at Microsoft.Moles.Runner.MolesRunner.LaunchRunnerEntryPoint(MolesRunnerOptions options)
   at Microsoft.Moles.Runner.MolesRunner.RunnerMain(String[] args)
   at Microsoft.Moles.Runner.Program.Main(String[] args)
```

**Comment by amirrajan** [comment]
No activity.
